FROM node:20-alpine

WORKDIR /app

# Install dependencies
RUN apk add --no-cache libc6-compat

# Copy package files
COPY package.json package-lock.json ./

# Install all dependencies (including dev)
RUN npm ci

# Copy app source
COPY . .

EXPOSE 3001

ENV PORT=3001

CMD ["npm", "run", "dev"]
