apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onesign.fullname" . }}-api
  labels:
    {{- include "onesign.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: api
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: api
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.api.service.port }}
          envFrom:
            - secretRef:
                name: {{ include "onesign.fullname" . }}-secrets
          env:
            - name: ASPNETCORE_URLS
              value: http://+:{{ .Values.api.service.port }}
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.config.aspnetEnvironment | quote }}
          readinessProbe:
            httpGet:
              path: /health/ready
              port: {{ .Values.api.service.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: {{ .Values.api.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
