apiVersion: v1
kind: Secret
metadata:
  name: {{ include "onesign.fullname" . }}-secrets
  labels:
    {{- include "onesign.labels" . | nindent 4 }}
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: {{ printf "Server=%s;Database=Onesign;User Id=sa;Password=%s;TrustServerCertificate=True" .Values.config.sqlServerHost .Values.secrets.sqlPassword | quote }}
  Jwt__SecretKey: {{ .Values.secrets.jwtSecret | quote }}
  Email__Provider: {{ .Values.config.emailProvider | quote }}
  Email__SendGrid__ApiKey: {{ .Values.secrets.emailSendGridApiKey | quote }}
  Email__Smtp__Password: {{ .Values.secrets.smtpPassword | quote }}
