namespace Onesign.Modules.Audit.Domain.Enums;

public enum AuditEventType
{
    UserLogin = 1,
    UserLogout = 2,
    UserCreated = 3,
    UserUpdated = 4,
    UserDeleted = 5,
    UserInvited = 6,
    UserDisabled = 7,
    UserEnabled = 8,
    TenantCreated = 9,
    TenantUpdated = 10,
    TenantDeleted = 11,
    TenantStatusChanged = 12,
    ApplicationCreated = 13,
    ApplicationUpdated = 14,
    ApplicationDeleted = 15,
    ApplicationClientSecretAdded = 18,
    ApplicationClientSecretRemoved = 19,
    PasswordChanged = 16,
    PasswordReset = 17,
    OrgUnitCreated = 20,
    OrgUnitUpdated = 21,
    OrgUnitDeleted = 22,
    OrgUnitMoved = 23,
    UserOrgUnitAssigned = 24,
    UserOrgUnitRemoved = 25,
    ApplicationOrgUnitAssigned = 26,
    ApplicationOrgUnitRemoved = 27,
    DelegatedAdminCreated = 28,
    DelegatedAdminRemoved = 29,

    // Security Events (Phase 13)
    SecurityBreach = 100,
    SuspiciousActivity = 101,
    FailedLoginAttempt = 102,
    AccountLockout = 103,
    RateLimitExceeded = 104,
    UnauthorizedAccess = 105,
    TokenCompromised = 106,
    CertificateExpiring = 107,
    CertificateExpired = 108,
    MfaEnrolled = 109,
    MfaDisabled = 110,
    MfaBypass = 111,
    ApiKeyCreated = 112,
    ApiKeyRevoked = 113,
    IpBlocked = 114,
    IpUnblocked = 115,
    TenantSuspended = 116,
    TenantReactivated = 117,
    DataExportRequested = 118,
    DataDeletionRequested = 119,
    PrivilegeEscalation = 120,
    ConfigurationChanged = 121,
    SecurityPolicyViolation = 122,
    AnomalousPattern = 123,
    UserLoggedIn = 124,
    LoginFailed = 125,
    DataAnonymized = 126,
    DataDeleted = 127,
    DataExported = 128
}

