<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="MediatR" Version="13.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.0" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.3.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Onesign.Shared\Onesign.Shared.csproj" />
    <ProjectReference Include="..\Onesign.Modules.Tenants\Onesign.Modules.Tenants.csproj" />
    <ProjectReference Include="..\Onesign.Modules.Identity\Onesign.Modules.Identity.csproj" />
    <ProjectReference Include="..\Onesign.Modules.Applications\Onesign.Modules.Applications.csproj" />
    <ProjectReference Include="..\Onesign.Modules.Audit\Onesign.Modules.Audit.csproj" />
  </ItemGroup>

</Project>
