// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Onesign.Data.Contexts;

#nullable disable

namespace Onesign.Api.Migrations
{
    [DbContext(typeof(OnesignDbContext))]
    [Migration("20251119100000_AddPhase24To30Modules")]
    partial class AddPhase24To30Modules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // This is a partial model snapshot - EF Core will merge with existing snapshot
            // Full model snapshot should be regenerated using dotnet ef migrations
#pragma warning restore 612, 618
        }
    }
}
