using System.CommandLine;
using System.CommandLine.Binding;
using System.CommandLine.Invocation;
using System.CommandLine.Parsing;
using System.Text.Json;

namespace Onesign.Cli.Commands;

public class ConfigCommand : Command
{
    public ConfigCommand() : base("config", "Manage CLI configuration")
    {
        Add(new SetServerCommand());
        Add(new SetClientCommand());
        Add(new ShowConfigCommand());
        Add(new ExportConfigCommand());
        Add(new ClearConfigCommand());
    }
}

public class ExportConfigCommand : Command
{
    public ExportConfigCommand() : base("export", "Export .env and appsettings.json snippets")
    {
        var formatOption = new Option<string>("--format", "-f")
        {
            Description = "Output format: env, appsettings, or all (default: all)",
            DefaultValueFactory = _ => "all"
        };

        var outputOption = new Option<string?>("--output", "-o")
        {
            Description = "Output directory (default: current directory)"
        };

        Add(formatOption);
        Add(outputOption);

        this.SetAction((ParseResult parseResult) =>
        {
            var format = parseResult.GetValue(formatOption) ?? "all";
            var output = parseResult.GetValue(outputOption);
            HandleExport(format, output);
        });
    }

    private static void HandleExport(string format, string? outputDir)
    {
        try
        {
            var config = CliConfig.Load();
            if (string.IsNullOrEmpty(config.BaseUrl))
            {
                Console.WriteLine("Error: No server configured. Run 'onesign config set-server <url>' first.");
                return;
            }

            var directory = string.IsNullOrWhiteSpace(outputDir)
                ? Directory.GetCurrentDirectory()
                : Path.GetFullPath(outputDir);

            if (!Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            var normalized = format.Trim().ToLowerInvariant();
            var writeEnv = normalized is "env" or "all";
            var writeAppSettings = normalized is "appsettings" or "appsettings.json" or "all";

            if (!writeEnv && !writeAppSettings)
            {
                Console.WriteLine("Error: format must be env, appsettings, or all.");
                return;
            }

            if (writeEnv)
            {
                var envPath = Path.Combine(directory, ".env.onesign");
                File.WriteAllText(envPath, ConfigExportWriter.BuildEnvFile(config));
                Console.WriteLine($"Wrote {envPath}");
            }

            if (writeAppSettings)
            {
                var appSettingsPath = Path.Combine(directory, "appsettings.onesign.json");
                File.WriteAllText(appSettingsPath, ConfigExportWriter.BuildAppSettingsJson(config));
                Console.WriteLine($"Wrote {appSettingsPath}");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}

internal static class ConfigExportWriter
{
    public static string BuildEnvFile(CliConfig config)
    {
        var authority = config.BaseUrl ?? "";
        var clientId = config.ClientId ?? "";
        var clientSecret = config.ClientSecret ?? "";

        return string.Join('\n', new[]
        {
            "# Generated by onesign-cli config export",
            $"ONESIGN_AUTHORITY={authority}",
            $"ONESIGN_CLIENT_ID={clientId}",
            $"ONESIGN_CLIENT_SECRET={clientSecret}",
            "ONESIGN_SIGNING_KEY=",
            "",
            "# Node.js (@onesign/sdk-node)",
            "# authority, audience/clientId, signingKey map to ONESIGN_* above",
            "",
            "# ASP.NET Core (Onesign.Sdk.AspNetCore)",
            "# Merge appsettings.onesign.json into appsettings.json",
        });
    }

    public static string BuildAppSettingsJson(CliConfig config)
    {
        var payload = new
        {
            Onesign = new
            {
                Authority = config.BaseUrl ?? "",
                Audience = config.ClientId ?? "",
                ClientId = config.ClientId ?? "",
                SigningKey = ""
            },
            ConnectionStrings = new
            {
                DefaultConnection = "Server=localhost;Database=MyApp;Trusted_Connection=True;TrustServerCertificate=True"
            }
        };

        return JsonSerializer.Serialize(payload, new JsonSerializerOptions { WriteIndented = true });
    }
}

public class SetServerCommand : Command
{
    public SetServerCommand() : base("set-server", "Set the OneSign server URL")
    {
        var urlArgument = new Argument<string>("url")
        {
            Description = "Server URL (e.g., https://auth.example.com)"
        };

        Add(urlArgument);

        this.SetAction((ParseResult parseResult) =>
        {
            var url = parseResult.GetValue(urlArgument);
            HandleSetServer(url!);
        });
    }

    private void HandleSetServer(string url)
    {
        try
        {
            if (!Uri.TryCreate(url, UriKind.Absolute, out var uri))
            {
                Console.WriteLine("Error: Invalid URL format.");
                return;
            }

            var config = CliConfig.Load();
            config.BaseUrl = uri.ToString().TrimEnd('/');
            config.Save();

            Console.WriteLine($"Server URL set to: {config.BaseUrl}");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}

public class SetClientCommand : Command
{
    public SetClientCommand() : base("set-client", "Set client credentials")
    {
        var clientIdOption = new Option<string>("--client-id", "-i")
        {
            Description = "Client ID",
            Arity = ArgumentArity.ExactlyOne
        };

        var clientSecretOption = new Option<string>("--client-secret", "-s")
        {
            Description = "Client Secret",
            Arity = ArgumentArity.ExactlyOne
        };

        Add(clientIdOption);
        Add(clientSecretOption);

        this.SetAction((ParseResult parseResult) =>
        {
            var clientId = parseResult.GetValue(clientIdOption);
            var clientSecret = parseResult.GetValue(clientSecretOption);
            HandleSetClient(clientId!, clientSecret!);
        });
    }

    private void HandleSetClient(string clientId, string clientSecret)
    {
        try
        {
            var config = CliConfig.Load();
            config.ClientId = clientId;
            config.ClientSecret = clientSecret;
            config.Save();

            Console.WriteLine("Client credentials saved successfully.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}

public class ShowConfigCommand : Command
{
    public ShowConfigCommand() : base("show", "Show current configuration")
    {
        var showSecretsOption = new Option<bool>("--show-secrets")
        {
            Description = "Show secret values"
        };

        Add(showSecretsOption);

        this.SetAction((ParseResult parseResult) =>
        {
            var showSecrets = parseResult.GetValue(showSecretsOption);
            HandleShowConfig(showSecrets);
        });
    }

    private void HandleShowConfig(bool showSecrets)
    {
        try
        {
            var config = CliConfig.Load();

            Console.WriteLine("Current Configuration:");
            Console.WriteLine(new string('-', 50));
            Console.WriteLine($"Server URL:     {config.BaseUrl ?? "(not set)"}");
            Console.WriteLine($"Client ID:      {config.ClientId ?? "(not set)"}");

            if (showSecrets)
            {
                Console.WriteLine($"Client Secret:  {config.ClientSecret ?? "(not set)"}");
            }
            else
            {
                Console.WriteLine($"Client Secret:  {(string.IsNullOrEmpty(config.ClientSecret) ? "(not set)" : "********")}");
            }

            Console.WriteLine();
            Console.WriteLine("Authentication Status:");
            Console.WriteLine(new string('-', 50));

            if (!string.IsNullOrEmpty(config.AccessToken))
            {
                var expired = config.TokenExpiresAt.HasValue && config.TokenExpiresAt.Value <= DateTimeOffset.UtcNow;
                Console.WriteLine($"Logged in:      Yes");
                Console.WriteLine($"Token Expires:  {config.TokenExpiresAt?.ToString("yyyy-MM-dd HH:mm:ss") ?? "Unknown"}");
                Console.WriteLine($"Token Status:   {(expired ? "Expired" : "Valid")}");
            }
            else
            {
                Console.WriteLine($"Logged in:      No");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}

public class ClearConfigCommand : Command
{
    public ClearConfigCommand() : base("clear", "Clear all configuration")
    {
        var forceOption = new Option<bool>("--force", "-f")
        {
            Description = "Skip confirmation"
        };

        Add(forceOption);

        this.SetAction((ParseResult parseResult) =>
        {
            var force = parseResult.GetValue(forceOption);
            HandleClearConfig(force);
        });
    }

    private void HandleClearConfig(bool force)
    {
        try
        {
            if (!force)
            {
                Console.Write("Are you sure you want to clear all configuration? (y/N): ");
                var response = Console.ReadLine();
                if (response?.ToLower() != "y")
                {
                    Console.WriteLine("Cancelled.");
                    return;
                }
            }

            var configPath = Path.Combine(
                Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),
                ".onesign",
                "config.json");

            if (File.Exists(configPath))
            {
                File.Delete(configPath);
            }

            Console.WriteLine("Configuration cleared successfully.");
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
